 export default { //Persian traslation file 
        name: 'fa',//Iran-Farsi
        strings: {
            lineColor: 'L',
            lineColorFull: 'رنگ خظ',
            fillColor: 'F',
            fillColorFull: 'رنگ داخل',
            alpha: 'A',
            alphaFull: 'شفاف',
            lineWidth: 'W',
            lineWidthFull: 'عرض خط',
            arrowLength: 'L',
            arrowLengthFull: 'طول بردار',
            eraserWidth: 'E',
            eraserWidthFull: 'عرض پاککن',
            textColor: 'C',
            textColorFull: 'رنگ متن',
            fontSize: 'S',
            fontSizeFull: 'اندازه متن',
            fontStrokeSize: 'St',
            fontStrokeSizeFull: 'عرض حاشیه',
            fontStyle: 'FS',
            fontStyleFull: 'حالت فونت',
            fontName: 'F',
            fontNameFull: 'نام فونت',
            textStrokeColor: 'SC',
            textStrokeColorFull: 'رنگ حاشیه',
            apply: 'اعمال',
            cancel: 'انصراف',
            close: 'بستن',
            clear: 'پاک کردن',
            width: 'عرض',
            height: 'طول',
            keepRatio: 'نگهداشتن نسبت طول/عرض',
            fillPageWith: 'پرکردن صفحه با رنگ پس زمینه',
            pixelSize: 'P',
            pixelSizeFull: 'اندازه نقطه',
            resizeScale: 'مقیاس',
            resizeResize: 'تغییر اندازه',
            backgroundColor: 'رنگ پس زمینه',
            pixelizePixelSize: 'اندازه پیکس شطرنجی کردن' ,
            language: 'زبان',
            wrongPixelSizeValue:
            'اندازه پیکسل اشتباه است. به طور مثال \'20%\' که به معنی اندازه 1/5 of ' +
            'محدوده انتخاب شده است, یا \'4\' به معنی 4 px است.',
            tools: {
                crop: 'بریدن تصویر به محدوده انتخاب شده',
                pixelize: 'پیکسی کردن محدوده انتخاب شده',
                rect: 'ترسیم مستطیل',
                ellipse: 'کشیدن نقطه چین',
                line: 'ترسیم خط',
                arrow: 'ترسیم بردار',
                rotate: 'چرخاندن تصویر',
                save: 'ذخیره تصویر',
                load: 'بارگذازی تصویر',
                text: 'گذاشتن متن',
                brush: 'قلم مو',
                resize: 'تغییر سایز یا مقیاس',
                open: 'باز کردن تصویر',
                select: 'انتخاب محدوده',
                close: 'بستن محیط ترسیم',
                eraser: 'پاک کردن',
                settings: 'تنظیمات',
                undo: 'باطل کردن',
                redo: 'انجام دوباره',
            },
            pasteOptions: {
                fit: 'جایگزین کردن همه',
                extend_down: 'گسترش به پایین',
                extend_right: 'گسترش به راست',
                extend: 'گسترش',
                over: 'چسباندن روی',
                how_to_paste: 'چگونه چسبانده؟',
            },
        }
    }
